spring:
  application:
    name: houseclash-backend

  datasource:

    url: ${DB_URL:jdbc:postgresql://db:5432/houseclash_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: false

server:
  port: 8080
  error:
    include-message: always